name: Node.js Test - API

on:
  push:
    branches:
      - main
  workflow_dispatch: {} # Add this manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

     

      - name: Install API Dependencies
        run: npm install
        working-directory: ./backend

      - name: Run API Tests
        run: npm test
        working-directory: ./backend
